# Without parralism enabled
# version: 2.1
# jobs:
#   test_e2e:
#     docker:
#       - image: mcr.microsoft.com/playwright:v1.17.1-focal
#     resource_class: medium
#     environment:
#       NODE_ENV: development
#     working_directory: ~/repo

#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             - v1-dependencies-
#       - run: npm ci
#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}
#       - run: npm run pw:e2e
#       - store_artifacts:
#           path: ~/repo/playwright/test-results
#       - store_artifacts:
#           path: ~/repo/playwright/test-report

# With parallelism enabled
version: 2.1
jobs:
  test_e2e:
    docker:
      - image: mcr.microsoft.com/playwright:v1.17.1-focal
    parallelism: 3
    resource_class: medium
    environment:
      NODE_ENV: development
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run pw:e2e -- --shard $CIRCLE_NODE_INDEX/$CIRCLE_NODE_TOTAL --workers=1
      - store_artifacts:
          path: ~/repo/playwright/test-results
      - store_artifacts:
          path: ~/repo/playwright/test-report
