version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.17.1-focal
    environment:
      NODE_ENV: development
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run pw:e2e
      - store_artifacts:
          path: ~/repo/playwright/test-results
      - store_artifacts:
          path: ~/repo/playwright/test-report
